### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by ghost** [BetsyTang/ATEPP#2]
Hello, (I'm only a musician, not an expert in programming) but I got interested in the fact that note durations are more accurate in the midis you provide rather than in Bytedance's original system. I was wondering if you altered their method to achieve those results, if you want to comment on that a little! And I also can't wait to try your system, may I ask, will you release it soon? Thanks for the last response.

**Comment by anusfoil** [comment]
Hi @xileflirba, thanks for your interest! We altered Bytedance's system a little bit by training jointly the note and pedal model, for the details please take a look at [our paper](https://ismir2022program.ismir.net/poster_70.html) section 3.3. This actually sacrifices the overall accuracy a bit, but it does provides more information on the note offset, for performance research. The code and trained model is actually in the [repository](https://github.com/BetsyTang/ATEPP/tree/master/piano_transcription-master), you can download the entire folder and run inference with the trained model 30000_iterations.pth. The codebase structure is almost the same as the Bytedance one.

**Comment by ghost** [comment]
Thank you for your response! I see, it's an interesting approach! Thanks
